create database MusicData;


use MusicData;


create table Music(
                      MusicId int PRIMARY KEY,
                      MusicName char (50),
                      Author char(50),
                      Years char(4),
                      Types char(50)
);
INSERT into Music VALUES  (1, 'La Lung', 'Vu','2017', 'Love'),
                          (2, 'Cuan cho anh mot dieu di', 'MCK', '2022','Love'),
                          (3,'Beautiful Girls','Sean Kingston','2010', 'Jazz'),
                          (4,'Sweet Emotion', 'Aerosmith ','1975','Rock'),
                          (5,'Quan Tai HU', ' young milo','2021', 'Choi Do')	,
                          (6, 'Chim Sau', 'MCK','2017', 'Love'),
                          (7, 'Bad Trip', 'MCK','2017', 'Love'),
                          (8, 'Flex', 'MCK','2017', 'Love'),
                          (9, 'Suy', 'MCK','2017', 'Love'),
                          (10,'Neu Ma 0 Phai Anh', 'Wxrdie','2021', 'Choi Do'),
                          (11,'HARDER', 'Wxrdie','2021', 'Choi Do')	,
                          (12,'HOT', 'Wxrdie','2021', 'Choi do')	,
                          (13,'Quay Xe', 'Wxrdie','2021', 'Choi do')	,
                          (14,'Tan Ra', 'Sol7 ','2022','Love'),
                          (15,'Ngan Ngui', 'Sol7 ','2022','Love'),
                          (16,'Icy Heart', 'Sol7 ','2022','Love'),
                          (17,'Chag The Biet', 'Sol7 ','2022','Love'),
                          (18,'Ice Man', 'Sol7 ','2022','Love'),
                          (19,'OK', 'Binz ','2020','Love'),
                          (20,'Krazy', 'Binz ','2020','Love'),
                          (21,'They Said', 'Binz ','2020','Love'),
                          (22,'Bigcityboi', 'Binz ','2020','Love'),
                          (23,'Saltt ON','Robber','2022', 'Choi do'),
                          (24,'Forest Gump','Robber','2022', 'Choi do'),
                          (25,'Lilyhammer','Robber','2022', 'Choi do'),
                          (26, 'Pray', 'Lil Wuyn','2021', 'Love'),
                          (27, 'Don Waste My Time', 'Lil Wuyn','2021', 'Love'),
                          (28,'I Don Know','RPT Lake','2022', 'Love'),
                          (29,'Loop', 'Coldzy ','2020','Rock'),
                          (30,'Anh hong Hieu', ' young milo','2021', 'Choi do')	,
                          (31, 'The Box Show', 'MCK','2020', 'Nguoi choi he chien'),
                          (32, 'Lop 13', 'Tage', '2020','Love'),
                          (33,'Mua Roi','RPT Lake','2022', 'Choi do'),
                          (34,'Choi do', 'MCK ','2020','Choi do'),
                          (35,'Buong Hang', 'young milo','2020', 'Choi do'),
                          (36, 'Sicko Mode', 'Travis Scott','2019', 'Love'),
                          (37, 'UaYYY', 'RAPITAL', '2021','Nguoi choi he chien'),
                          (38,'Ngu trong phong thu','RAPITAL','2022', 'Nguoi choi he chien'),
                          (39,'Thich em hoi nhieu', 'Wren Evans ','2022','Love'),
                          (40,'NGTANOISE', ' Vsoul','2021', 'Love')	,
                          (41, 'Ha Noi Xin', 'LK','2020', 'Nguoi choi he chien'),
                          (42, 'OCEAN', 'MCK', '2022','Choi do'),
                          (43,'Di trong mua he','Den','2022','Chill'),
                          (44,'Mang Tien Ve Cho ME', 'Den ','2022','Chill'),
                          (45,'Loi Nho', 'Den ','2020','Chill'),
                          (46,'Mot Trieu Like', 'Den ','2020','Chill'),
                          (47,'Muoi Nam', 'Den ','2020','Chill'),
                          (48,'Bai Nay Chill Phet', 'Den ','2020','Chill'),
                          (49,'Hai Trie Nam', 'Den ','2020','Chill'),
                          (50,'Tron Tim', 'Den ','2020','Chill');